# Generated by Django 4.1.7 on 2023-03-01 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
