# Generated by Django 4.1.7 on 2023-03-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprject', '0002_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
