# Generated by Django 4.1.7 on 2023-03-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprject', '0002_student_phone_num_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
