# Generated by Django 4.1.7 on 2023-03-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprject', '0003_remove_student_phone_num_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
